import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import "react-h5-audio-player/lib/styles.css";
import TableRadioStations from "../components/table";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>a.m. cat instrumental radio</title>

        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>a.m. cat radio</h1>
        <Image
          src={"/purr-party-hard.png"}
          alt="gatos ouvindo rádio"
          width={300}
          height={300}
        />

        <p className={styles.description}>_instrumental radio stations </p>
        <div>
          <TableRadioStations />
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{" "}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
        {/* <p>
        Illustration by{" "}
        <span  className={styles.logo}>
          <a href="https://icons8.com/illustrations"> Ouch!      </a>
        </span>
        </p>
       <p>
           {"      Made with "}
        <span role="img" aria-label="emoticon musical note"> 🎵</span>
       </p> */}
      </footer>
    </div>
  );
}
